### ISSUE TITLE
Images are not displayed in the app

### ISSUE THREAD

**Issue by hitvoice** [paulbjensen/lens-photo-app#2]
I tried to run the app with the `nw` command and `nwbuild -r .` command. The app launched successfully, but the images weren't displayed correctly. The types of the images are jpeg and png.
<img width="512" alt="qq20161001-0 2x" src="https://cloud.githubusercontent.com/assets/13765633/19013095/4030e990-87fa-11e6-94c0-f6a36e4b0faf.png">
<img width="512" alt="qq20161001-1 2x" src="https://cloud.githubusercontent.com/assets/13765633/19013096/409f29dc-87fa-11e6-99f2-38caf98ad6bc.png">

I'm using OSX EI Capitan 10.11.6. Version of nw: 0.17.6. Version of Node.js: 4.6.0.

**Comment by paulbjensen** [comment]
Hi,

Thanks for the message. I think that this bug could be because the app hasn't been updated to support the latest version of NW.js. When I made the app, I was using I think either 0.10 or 0.12 for NW.

What I will do now is try and get the app working with the latest stable version of NW.js.

**Comment by hitvoice** [comment]
Thank you for your reply and I'm looking forward to your progress!

**Comment by paulbjensen** [comment]
Hi, I figured out how to fix the display of the images. It turns out that in newer versions of NW.js, you need to provide the file:// protocol in the img src attribute, otherwise the application won't be able to locate the file.

I've pushed the code up to GitHub so that should work fine. Let me know how you get on.

**Comment by hitvoice** [comment]
It's fixed. Thanks a lot!!
